version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.config:/config
    networks:
      - traefik_web
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.routers.heimdall.rule: 'Host(`heimdall.${DOMAIN_URL}`,`www.${DOMAIN_URL}`,`${DOMAIN_URL}`)'
      traefik.http.services.heimdall.loadbalancer.server.port: 80

networks:
  traefik_web:
    external: true
