version: '3.7'
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: '/run/secrets/mysql-user'
      MYSQL_DATABASE_FILE: '/run/secrets/mysql-database'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    secrets:
      - mysql-user
      - mysql-database
      - mysql-password
    networks:
      - lan 
    volumes: 
      - db:/var/lib/mysql


  blog:
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER_FILE: '/run/secrets/mysql-user'
      WORDPRESS_DB_PASSWORD_FILE: '/run/secrets/mysql-password'
      WORDPRESS_DB_NAME_FILE: '/run/secrets/mysql-database'
    secrets:
      - mysql-user
      - mysql-database
      - mysql-password
    networks:
      - lan
      - traefik_web
    volumes:
      - html:/var/www/html
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.rule: 'Host(`wordpress.mydomain.com`)'
      traefik.http.services.wordpress.loadbalancer.server.port: 80
      # remove Server and X-Powered-By headers
      traefik.http.middlewares.wp-headers.headers.customresponseheaders.Server: ''
      traefik.http.middlewares.wp-headers.headers.customresponseheaders.X-Powered-By: ''
      # add some sec headers
      traefik.http.middlewares.wp-headers.headers.contentsecuritypolicy: "default-src 'self' data: ; script-src 'self' 'unsafe-inline' ; style-src 'self' 'unsafe-inline' fonts.googleapis.com https://code.jquery.com ; font-src 'self' fonts.gstatic.com data: ; img-src 'self' data: https://code.jquery.com"
      traefik.http.middlewares.wp-headers.headers.referrerpolicy: "same-origin"
      traefik.http.middlewares.wp-headers.headers.featurepolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"
      traefik.http.routers.wordpress.middlewares: 'wp-headers'
      # whitelist access to /wp-admin, replace X.X.X.X with your public IP  
      # if you dont need restrict wp-admin, remove or comment next lines   
      traefik.http.middlewares.wp-ipwhitelist.ipwhitelist.sourcerange: 'X.X.X.X/32'
      traefik.http.routers.wordpress-admin.rule: 'Host(`wordpress.mydomain.com`) && (Path(`/wp-admin`)|| Path(`/wp-login.php`))'
      traefik.http.routers.wordpress-admin.middlewares: 'wp-ipwhitelist'
      
volumes:
  db:
  html:

networks:
  traefik_web:
    external: true

  lan:

secrets:
  mysql-user:
    file: ./secrets/mysql-user.txt

  mysql-database:
    file: ./secrets/mysql-database.txt

  mysql-password:
    file: ./secrets/mysql-password.txt
