version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8080 config.wsgi'
    environment:
      - DEBUG=0
#      - DATABASE_URL=postgresql://django_traefik:django_traefik@db:5432/django_traefik
      - DJANGO_ALLOWED_HOSTS=.${DOMAIN_URL}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.rule=Host(`django.${DOMAIN_URL}`)"
      - "traefik.http.services.django.loadbalancer.server.port=8080"
    networks:
      - traefik_web
      - lan
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_django_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - lan


volumes:
  postgres_django_data:

networks:
  traefik_web:
    external: true
  lan: