version: "3.7"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- SERVERURL=${DOMAIN_URL} #optional
      #- SERVERPORT=51820 #optional
      - PEERS=1 #optional #TODO add 2 peer for mobile connection
      #- PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=192.168.123.0 #172.25.0.1/24 #optional
      #- LOG_CONFS=true #optional
    volumes:
      - ./.config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks: 
     VPN:


networks:
  VPN:
    ipam:
      config:
      - subnet: 192.168.123.0/24